image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest
stages:
  - test
before_script:
  - cd SmartphoneApps/Saarromanus
  - npm ci
jest-tests:
  stage: test
  script:
    - npx jest --ci