language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - cd SmartphoneApps/Saarromanus
<<<<<<< Updated upstream
  - npm install -g npm@latest
=======
  - npm install -g npm@6.12.0
>>>>>>> Stashed changes
script:
  - npm ci
  - npx jest --ci